"""Machinery shared by the two drivers that run on hardware we operate.

`subprocess` and `container` differ in exactly one thing — whether an argv is
wrapped in `docker run` — and agree on everything else: where a session's files
live, how output is captured and streamed, how a wall-clock timeout kills a
process that has stopped listening, and how a chart written to disk becomes an
artifact the UI can render. Keeping that agreement in one module is what stops
the two drivers drifting into two different products.

The artifact convention is the interesting part. E2B hands back structured
results because it runs a notebook kernel; a plain `python script.py` does not.
Rather than bolt a kernel onto both drivers, the contract here is the one every
data scientist already follows: **write your figure to a file**. After each
execution the session directory is diffed and anything new that looks like an
image or a document becomes an `Artifact`. That works identically for a
subprocess and a container, needs no cooperation from the generated code beyond
`plt.savefig("chart.png")`, and survives the process exiting.
"""
from __future__ import annotations

import os
import resource
import subprocess
import threading
import time
from pathlib import Path
from typing import Callable, Dict, List, Mapping, Optional, Sequence, Tuple

from .types import (
    Artifact,
    ArtifactKind,
    ExecResult,
    FileEntry,
    OutputSink,
    SandboxError,
    SandboxHandle,
)

#: Extensions harvested from the session directory after an execution, mapped to
#: the artifact kind and mime type the UI renders them with. Text and data files
#: are deliberately absent: a run that writes a CSV should not turn it into an
#: inline artifact, because the interesting ones are what a human looks at.
ARTIFACT_TYPES: Dict[str, Tuple[ArtifactKind, str]] = {
    ".png": ("png", "image/png"),
    ".jpg": ("jpeg", "image/jpeg"),
    ".jpeg": ("jpeg", "image/jpeg"),
    ".svg": ("svg", "image/svg+xml"),
    ".pdf": ("pdf", "application/pdf"),
    ".html": ("html", "text/html"),
}

#: A plotting loop can emit hundreds of figures, and each one costs a round trip
#: and a row. Harvest the newest and say how many were dropped rather than
#: silently truncating — a caller that thinks it got everything is worse off than
#: one told it did not.
MAX_ARTIFACTS = 12
MAX_ARTIFACT_BYTES = 8 * 1024 * 1024


def session_root(base: Path, external_id: str) -> Path:
    """The host directory backing one session.

    `external_id` is generated by the driver, never supplied by a caller, but the
    containment check is here anyway: this function turns a string into a
    filesystem path, and every such function in this codebase is one traversal
    bug away from being the interesting one in an incident report.
    """
    if _bad_id(external_id):
        raise SandboxError("invalid sandbox id")
    path = (base / external_id).resolve()
    if not str(path).startswith(str(base.resolve()) + os.sep):
        raise SandboxError("invalid sandbox id")
    return path


def _bad_id(external_id: str) -> bool:
    """A driver id that must not be turned into a path. A NUL is in here beside
    the traversal characters because it fails *differently*: `Path` operations on
    a NUL-bearing string raise `ValueError`, not `OSError`, so an unlink or
    resolve would throw straight past the `OSError` handlers a caller like
    `remove_session_env` relies on — turning a bad id into an escaped exception
    that skips the rest of teardown."""
    return (
        not external_id
        or "\x00" in external_id
        or "/" in external_id
        or "\\" in external_id
        or external_id.startswith(".")
    )


def ensure_session_root(base: Path, external_id: str, *, mode: int = 0) -> Path:
    """The host directory backing one session, created if it is not there.

    `mode` exists for the container driver, which bind-mounts this directory into
    a container running as an unprivileged uid that is not the API's. A bind
    mount keeps host ownership, so without a widened mode the sandbox can read
    the code we stage but cannot create `chart.png` next to it — every execution
    that writes a file fails while every print-only one passes, which is the
    shape of bug a smoke test never catches. mkdir's own mode argument is masked
    by the process umask, so the chmod has to be a separate call.

    A caller that passes nothing gets the default umask behaviour, which is what
    the subprocess driver wants: it runs as the API user and widening the mode
    there would be a permission grant nobody needs.
    """
    path = session_root(base, external_id)
    path.mkdir(parents=True, exist_ok=True)
    if mode:
        os.chmod(path, mode)
    return path


def _session_sidecar(base: Path, external_id: str, suffix: str) -> Path:
    """A file that belongs to a session but lives *beside* its directory.

    Deliberately outside `session_root(base, external_id)`, so it is invisible to
    the sandbox: `snapshot`/`harvest`/`list_files` only ever walk inside the
    session root, and the container mounts only that root — so a per-session env
    file placed here is never harvested as an artifact, never listed to the
    model, and never readable by the code running in the box. The id is
    driver-generated, but the same containment check `session_root` applies is
    applied here too, because this turns a string into a filesystem path.
    """
    if _bad_id(external_id):
        raise SandboxError("invalid sandbox id")
    return base / f".{external_id}{suffix}"


def write_session_env(base: Path, external_id: str, env: Mapping[str, str]) -> None:
    """Persist a session's environment, so a per-`docker run --rm` execution can
    reconstruct it — the local drivers hold no live machine to carry it.

    Written 0600 and beside the session directory rather than inside it: this is
    the one place decrypted secrets touch the local disk, and it must not inherit
    the 0777 the container driver widens the *session root* to for its bind mount.
    """
    import json

    path = _session_sidecar(base, external_id, ".env.json")
    payload = json.dumps(dict(env)).encode("utf-8")
    # Create 0600 from the first byte rather than write-then-chmod: the latter
    # leaves a window where the file exists under the umask's mode (typically
    # world-readable) with decrypted secrets already in it. O_CREAT's mode only
    # applies when the file is new, so an existing sidecar (a rotation overwrite)
    # is re-tightened with fchmod to be sure.
    fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    try:
        try:
            os.fchmod(fd, 0o600)
        except OSError:
            # A platform that refuses the chmod (rare) still gets the file; the
            # secret is no more exposed than the SQLite database beside it.
            pass
        os.write(fd, payload)
    finally:
        os.close(fd)


def remove_session_env(base: Path, external_id: str) -> None:
    """Delete a session's env sidecar. Called on teardown so the one place
    decrypted secrets touch local disk does not outlive the session that needed
    them — without this, a killed session's plaintext credentials would survive
    both rotation and deletion of the secret itself. Best-effort and idempotent:
    a missing file means the job is already done."""
    try:
        path = _session_sidecar(base, external_id, ".env.json")
    except SandboxError:
        return
    try:
        path.unlink()
    except FileNotFoundError:
        pass
    except OSError:
        pass


def read_session_env(base: Path, external_id: str) -> Dict[str, str]:
    """A session's persisted environment, or empty if none was written.

    Absent is the normal case for a session created before this existed, or one
    with no secrets — so a missing or unreadable file degrades to "no extra
    environment", never an error that would break every execution.
    """
    import json

    try:
        path = _session_sidecar(base, external_id, ".env.json")
    except SandboxError:
        return {}
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return {}
    try:
        parsed = json.loads(raw)
    except ValueError:
        return {}
    if not isinstance(parsed, dict):
        return {}
    return {str(k): str(v) for k, v in parsed.items()}


def _is_contained_regular_file(path: Path, root: Path) -> bool:
    """True only for a real file that genuinely lives under `root`.

    Every check here exists because the harvester runs on the HOST, as the API
    user, over the bind mount — outside every guarantee the container flags buy.
    Generated code cannot read /etc/passwd itself (--read-only, --cap-drop ALL,
    uid 65534), but it can create a symlink named chart.png pointing at it, and
    the harvester following that link reads the host file with the API's own
    authority and persists it as a workspace source.

    `is_file()`, `stat()` and `read_bytes()` all follow symlinks, so the link
    has to be rejected before any of them is called: `lstat` describes the link
    itself. `resolve()` is then belt-and-braces for a directory component that
    is itself a link.
    """
    try:
        if path.is_symlink() or not path.lstat().st_mode & 0o170000 == 0o100000:
            return False
        resolved = path.resolve()
        root_resolved = root.resolve()
    except OSError:
        return False
    return resolved == root_resolved or str(resolved).startswith(str(root_resolved) + os.sep)


def snapshot(directory: Path) -> Dict[Path, float]:
    """mtimes before an execution, so the diff afterwards finds what it wrote.

    Keyed on mtime rather than existence because overwriting `chart.png` on a
    second run is the common case, and an existence check would report it once
    and then never again.
    """
    seen: Dict[Path, float] = {}
    for path in directory.rglob("*"):
        if _is_contained_regular_file(path, directory):
            try:
                seen[path] = path.stat().st_mtime
            except OSError:
                continue
    return seen


def harvest_artifacts(
    directory: Path, before: Mapping[Path, float]
) -> Tuple[Tuple[Artifact, ...], int]:
    """Files created or rewritten by the execution, newest first.

    Returns (artifacts, dropped) so the caller can tell the user what it did not
    get back.
    """
    import base64

    candidates: List[Tuple[float, Path]] = []
    for path in directory.rglob("*"):
        if not _is_contained_regular_file(path, directory):
            continue
        if path.suffix.lower() not in ARTIFACT_TYPES:
            continue
        try:
            mtime = path.stat().st_mtime
        except OSError:
            continue
        if before.get(path) == mtime:
            continue
        candidates.append((mtime, path))

    candidates.sort(reverse=True)
    kept: List[Artifact] = []
    dropped = 0
    for _, path in candidates:
        if len(kept) >= MAX_ARTIFACTS:
            dropped += 1
            continue
        try:
            raw = path.read_bytes()
        except OSError:
            continue
        if len(raw) > MAX_ARTIFACT_BYTES:
            dropped += 1
            continue
        kind, mime = ARTIFACT_TYPES[path.suffix.lower()]
        # svg and html are text; the rest are binary and travel as base64, which
        # is what `Artifact.data` promises for those kinds.
        if kind in ("svg", "html"):
            data = raw.decode("utf-8", errors="replace")
        else:
            data = base64.b64encode(raw).decode("ascii")
        kept.append(
            Artifact(
                kind=kind,
                mime=mime,
                data=data,
                is_main=not kept,
                chart_json="",
            )
        )
    return tuple(kept), dropped


def rlimit_preexec(
    *, cpu_seconds: int, memory_mb: int, pids: int, fsize_mb: int
) -> Callable[[], None]:
    """Resource caps applied between fork and exec.

    These are a courtesy, not a boundary: they stop a runaway loop taking the
    machine down, and they stop nothing that is deliberately hostile. The
    boundary for the subprocess driver is `_guard_sandbox` refusing to let it run
    outside development; see ADR 0005.

    RLIMIT_AS rather than RLIMIT_DATA because numpy allocates by mapping, and a
    DATA limit lets a process map its way past the cap it was given.
    """

    def apply() -> None:  # pragma: no cover - runs in the forked child
        resource.setrlimit(resource.RLIMIT_CPU, (cpu_seconds, cpu_seconds + 5))
        limit = memory_mb * 1024 * 1024
        try:
            resource.setrlimit(resource.RLIMIT_AS, (limit, limit))
        except (ValueError, OSError):
            # macOS refuses RLIMIT_AS for some values. Losing the memory cap on a
            # developer laptop is survivable; failing to start is not.
            pass
        try:
            resource.setrlimit(resource.RLIMIT_NPROC, (pids, pids))
        except (ValueError, OSError):
            pass
        fsize = fsize_mb * 1024 * 1024
        resource.setrlimit(resource.RLIMIT_FSIZE, (fsize, fsize))
        resource.setrlimit(resource.RLIMIT_CORE, (0, 0))
        # Detach into a fresh process group so a timeout can kill the whole tree
        # rather than the parent of a process that has already forked away.
        os.setsid()

    return apply


def _pump(stream: object, stream_name: str, sink: List[str], on_output: OutputSink) -> None:
    """Drain one pipe, appending to `sink` and forwarding to `on_output`.

    A thread per pipe rather than select(), because the goal is to keep both
    pipes drained: a child that fills the stderr buffer while the parent reads
    only stdout deadlocks, and that failure looks exactly like a hung sandbox.
    """
    for line in iter(stream.readline, ""):  # type: ignore[attr-defined]
        sink.append(line)
        if on_output is not None:
            try:
                on_output(stream_name, line)
            except Exception:
                # A failing UI callback must not kill the execution that is
                # feeding it.
                pass


def run_process(
    argv: Sequence[str],
    *,
    cwd: Path,
    env: Mapping[str, str],
    timeout: float,
    on_output: OutputSink = None,
    preexec: Optional[Callable[[], None]] = None,
) -> ExecResult:
    """Run argv to completion or to the wall clock, whichever comes first.

    `env` is passed as the complete environment — `os.environ` is never merged
    in. That is the single most important line in this module: the parent
    process holds an OpenAI key, a database URL and the session-signing secret,
    and inheriting them by default is how generated code reads them.
    """
    started = time.monotonic()
    try:
        process = subprocess.Popen(  # noqa: S603 - argv list, shell=False
            list(argv),
            cwd=str(cwd),
            env=dict(env),
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            stdin=subprocess.DEVNULL,
            text=True,
            errors="replace",
            bufsize=1,
            preexec_fn=preexec,
            start_new_session=preexec is None,
        )
    except FileNotFoundError as exc:
        raise SandboxError(f"sandbox runtime not found: {argv[0]}") from exc
    except OSError as exc:
        raise SandboxError(f"could not start sandbox process: {exc.strerror}") from exc

    out: List[str] = []
    err: List[str] = []
    pumps = [
        threading.Thread(
            target=_pump, args=(process.stdout, "stdout", out, on_output), daemon=True
        ),
        threading.Thread(
            target=_pump, args=(process.stderr, "stderr", err, on_output), daemon=True
        ),
    ]
    for pump in pumps:
        pump.start()

    timed_out = False
    try:
        process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        timed_out = True
        _kill_tree(process)
        process.wait(timeout=10)
    for pump in pumps:
        pump.join(timeout=5)

    duration_ms = int((time.monotonic() - started) * 1000)
    stderr_text = "".join(err)
    error = ""
    if timed_out:
        # Reported as an error rather than a raised exception: a script that runs
        # too long is a result the model can act on by writing a faster one.
        error = f"timed out after {timeout:.0f}s"
    return ExecResult(
        stdout="".join(out),
        stderr=stderr_text,
        exit_code=process.returncode,
        error=error,
        traceback="",
        artifacts=(),
        duration_ms=duration_ms,
        truncated=False,
    )


class LocalProvider:
    """Shared base for the drivers whose session state is a host directory.

    Both `subprocess` and `container` model a session as a directory rather than
    a live machine, which is why neither has anything to pause and neither can
    orphan a running process between turns. Files persist; interpreter state does
    not. That is a real difference from E2B's notebook kernel and it is written
    down in ADR 0005 rather than smoothed over, because generated code that
    relies on a variable surviving between executions works there and fails here.
    """

    name = "local"

    def __init__(self, *, workdir: Path, env: Mapping[str, str]) -> None:
        self._workdir = workdir
        self._env = dict(env)

    # -- filesystem, identical for both drivers ---------------------------

    def _dir(self, handle: SandboxHandle) -> Path:
        return session_root(self._workdir, handle.external_id)

    def _process_env(self, handle: SandboxHandle) -> Dict[str, str]:
        """The environment a run actually gets: the frozen base folded with the
        secrets this session was created with.

        `self._env` is the scrubbed base every session shares; the per-session
        sidecar carries the workspace's decrypted secrets (`spec.env`), which the
        local drivers cannot keep in a live machine because there isn't one.

        The secret wins on a key collision (it is spread last), which would let a
        secret named `PATH` or `LD_PRELOAD` redirect the interpreter — so the
        create route refuses both policy keys and those process-steering names
        (`secrets.validate_name`). The precedence here is safe only because that
        validation holds; it is not a second line of defence.
        """
        return {**self._env, **read_session_env(self._workdir, handle.external_id)}

    def _resolve(self, root: Path, path: str) -> Path:
        """Map a sandbox-visible path onto the host, refusing to escape.

        Generated code names these paths, so this is a genuine attacker-controlled
        input even in the container driver, where a bind mount means a traversal
        would reach the host filesystem rather than the image's.
        """
        cleaned = path.lstrip("/")
        for prefix in ("workspace/", "home/user/"):
            if cleaned.startswith(prefix):
                cleaned = cleaned[len(prefix) :]
        target = (root / cleaned).resolve()
        if target != root and not str(target).startswith(str(root) + os.sep):
            raise SandboxError(f"path escapes the sandbox: {path}")
        return target

    def write_files(self, handle: SandboxHandle, files: Mapping[str, bytes]) -> None:
        root = ensure_session_root(self._workdir, handle.external_id)
        for path, data in files.items():
            target = self._resolve(root, path)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(data)

    def read_file(self, handle: SandboxHandle, path: str) -> bytes:
        target = self._resolve(self._dir(handle), path)
        try:
            return target.read_bytes()
        except FileNotFoundError as exc:
            raise SandboxError(f"no such file in sandbox: {path}") from exc
        except OSError as exc:
            raise SandboxError(f"could not read {path}: {exc.strerror}") from exc

    def list_files(
        self, handle: SandboxHandle, path: str, *, depth: int = 1
    ) -> Sequence[FileEntry]:
        root = self._dir(handle)
        target = self._resolve(root, path or "/")
        if not target.exists():
            return ()
        entries: List[FileEntry] = []
        for child in sorted(target.rglob("*") if depth > 1 else target.iterdir()):
            # lstat, and skip links entirely: stat() on a symlink reports the
            # size and existence of whatever it points at, leaking host paths
            # into a listing the model reads.
            if child.is_symlink():
                continue
            try:
                stat = child.lstat()
            except OSError:
                continue
            entries.append(
                FileEntry(
                    path="/" + str(child.relative_to(root)),
                    name=child.name,
                    is_dir=child.is_dir(),
                    size=0 if child.is_dir() else stat.st_size,
                )
            )
        return tuple(entries)

    def pause(self, handle: SandboxHandle) -> None:
        """No-op. A session is a directory; there is no process to snapshot."""

    def kill(self, handle: SandboxHandle) -> None:
        """Delete the session directory *and* its env sidecar. Idempotent — the
        reaper races an explicit delete, and a missing target means the job is
        already done.

        The sidecar is the one place decrypted secrets touch local disk; deleting
        it here is what keeps a killed session's plaintext credentials from
        outliving the session. It is removed unconditionally, even when the id is
        too malformed to name a session root, so a bad id can never strand it."""
        import shutil

        remove_session_env(self._workdir, handle.external_id)
        try:
            root = session_root(self._workdir, handle.external_id)
        except SandboxError:
            return
        shutil.rmtree(root, ignore_errors=True)


def _kill_tree(process: subprocess.Popen[str]) -> None:
    """SIGKILL the whole process group, not just the child we spawned.

    A timed-out script has usually stopped cooperating, so SIGTERM-then-wait
    mostly buys latency. And killing only the direct child orphans whatever it
    forked, which then keeps the pipes open and hangs the reader threads.
    """
    import signal

    try:
        os.killpg(os.getpgid(process.pid), signal.SIGKILL)
    except (ProcessLookupError, PermissionError):
        try:
            process.kill()
        except ProcessLookupError:
            pass
